In [1]:
import numpy as np
import pandas as pd


In [2]:
arr = [6,7,8,9]
print(type(arr))

<class 'list'>


In [3]:
a = np.array(arr)
print(type(a))

<class 'numpy.ndarray'>


In [4]:
print(a.shape)

(4,)


In [5]:
print(a.dtype)

int32


In [6]:
print(a.ndim)

1


In [7]:
b = np.array([[1,2,3], [4,5,6]])

In [8]:
print(b)

[[1 2 3]
 [4 5 6]]


In [9]:
print(b.ndim)

2


In [10]:
b.shape

(2, 3)

In [11]:
np.random.random((2,3))

array([[0.73992559, 0.27645579, 0.24527977],
       [0.76370168, 0.68476906, 0.81939759]])

In [12]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [13]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [14]:
#identity matrixes 3*3
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [15]:
Ist = [[35, 'Portugal', 94], [33, 'Argentina', 93], [30 , 'Brazil', 92]]

col = ['Age','Nationality','Overall']

In [ ]:
my_tuppy = (1,2,5,8)

my_tuppy[2] = 6


In [18]:
# read file
df=pd.read_csv("FoodBalanceSheets_E_Africa_NOFLAG.csv", encoding='latin-1')

In [19]:
df


Area Code      Area  Item Code           Item  Element Code  \
0              4   Algeria       2501     Population           511   
1              4   Algeria       2501     Population          5301   
2              4   Algeria       2901    Grand Total           664   
3              4   Algeria       2901    Grand Total           674   
4              4   Algeria       2901    Grand Total           684   
...          ...       ...        ...            ...           ...   
60938        181  Zimbabwe       2899  Miscellaneous          5142   
60939        181  Zimbabwe       2899  Miscellaneous           645   
60940        181  Zimbabwe       2899  Miscellaneous           664   
60941        181  Zimbabwe       2899  Miscellaneous           674   
60942        181  Zimbabwe       2899  Miscellaneous           684   

                                      Element             Unit     Y2014  \
0               Total Population - Both sexes     1000 persons  38924.00   
1                    Domestic supply quantity      1000 tonnes      0.00   
2               Food supply (kcal/capita/day)  kcal/capita/day   3377.00   
3      Protein supply quantity (g/capita/day)     g/capita/day     94.90   
4          Fat supply quantity (g/capita/day)     g/capita/day     80.06   
...                                       ...              ...       ...   
60938                                    Food      1000 tonnes     42.00   
60939     Food supply quantity (kg/capita/yr)               kg      3.06   
60940           Food supply (kcal/capita/day)  kcal/capita/day      3.00   
60941  Protein supply quantity (g/capita/day)     g/capita/day      0.10   
60942      Fat supply quantity (g/capita/day)     g/capita/day      0.04   

          Y2015     Y2016     Y2017     Y2018  
0      39728.00  40551.00  41389.00  42228.00  
1          0.00      0.00      0.00      0.00  
2       3379.00   3372.00   3341.00   3322.00  
3         94.35     94.72     92.82     91.83  
4         79.36     77.40     80.19     77.28  
...         ...       ...       ...       ...  
60938     46.00     33.00     19.00     16.00  
60939      3.33      2.35      1.33      1.08  
60940      4.00      3.00      1.00      1.00  
60941      0.11      0.08      0.04      0.04  
60942      0.05      0.03      0.02      0.01  

[60943 rows x 12 columns]

In [20]:
# to describe the dataset
df.describe()

Area Code     Item Code  Element Code          Y2014          Y2015  \
count  60943.000000  60943.000000  60943.000000   59354.000000   59395.000000   
mean     134.265576   2687.176706   3814.856456     134.196282     135.235966   
std       72.605709    146.055739   2212.007033    1567.663696    1603.403984   
min        4.000000   2501.000000    511.000000   -1796.000000   -3161.000000   
25%       74.000000   2562.000000    684.000000       0.000000       0.000000   
50%      136.000000   2630.000000   5142.000000       0.090000       0.080000   
75%      195.000000   2775.000000   5511.000000       8.340000       8.460000   
max      276.000000   2961.000000   5911.000000  176405.000000  181137.000000   

               Y2016          Y2017          Y2018  
count   59408.000000   59437.000000   59507.000000  
mean      136.555222     140.917765     143.758381  
std      1640.007194    1671.862359    1710.782658  
min     -3225.000000   -1582.000000   -3396.000000  
25%         0.000000       0.000000       0.000000  
50%         0.080000       0.100000       0.070000  
75%         8.430000       9.000000       9.000000  
max    185960.000000  190873.000000  195875.000000

In [21]:
df.sum()

Area Code                                                 8182547
Area            AlgeriaAlgeriaAlgeriaAlgeriaAlgeriaAlgeriaAlge...
Item Code                                               163764610
Item            PopulationPopulationGrand TotalGrand TotalGran...
Element Code                                            232488797
Element         Total Population - Both sexesDomestic supply q...
Unit            1000 persons1000 tonneskcal/capita/dayg/capita...
Y2014                                                 7.96509e+06
Y2015                                                 8.03234e+06
Y2016                                                 8.11247e+06
Y2017                                                 8.37573e+06
Y2018                                                 8.55463e+06
dtype: object

In [22]:
#to describe num of rows and columns
df.shape

(60943, 12)

In [23]:
#hat is the total sum of Animal Fat produced in 2014 and 2017 respectively?
df.groupby('Item')['Y2014'].sum()

Item
Alcohol, Non-Food        2403.00
Alcoholic Beverages    102410.11
Animal Products         11935.65
Animal fats            209460.54
Apples and products      9499.23
                         ...    
Vegetables, Other      155038.96
Vegetal Products       107145.19
Wheat and products     232670.13
Wine                     4497.36
Yams                   200396.96
Name: Y2014, Length: 119, dtype: float64

In [24]:
df.isna().sum()

Area Code          0
Area               0
Item Code          0
Item               0
Element Code       0
Element            0
Unit               0
Y2014           1589
Y2015           1548
Y2016           1535
Y2017           1506
Y2018           1436
dtype: int64

In [41]:
# Animal Fat produced in Y2017 = 269617.53
df.groupby('Item')['Y2017'].sum()

Item
Alcohol, Non-Food        2348.00
Alcoholic Beverages     95581.06
Animal Products         11547.65
Animal fats            269617.53
Apples and products     10198.90
                         ...    
Vegetables, Other      157752.59
Vegetal Products       107655.20
Wheat and products     240047.62
Wine                     4178.02
Yams                   229174.59
Name: Y2017, Length: 119, dtype: float64

In [27]:
#The Mean and Standard deviation across the whole dataset for the year 2015 are 135.236 and 1603.404
print(round(df.Y2015.mean(),3))
print(round(df.Y2015.std(),3))


135.236
1603.404


In [28]:
#The total number and percentage of missing data in 2016 to 2 decimal places are 1535 and 2.58 respectively
df.Y2016.isna().sum()

1535

In [29]:
round(((df.Y2016.isna().sum())/df.Y2016.count()) * 100, 2)

2.58

In [31]:
#From the correlation chart above year 2014 has the highest correlation with the Element code with correlation value = 0.024457
df.corr()

Area Code  Item Code  Element Code     Y2014     Y2015  \
Area Code      1.000000  -0.005159     -0.000209  0.006164  0.005472   
Item Code     -0.005159   1.000000     -0.024683  0.021722  0.020857   
Element Code  -0.000209  -0.024683      1.000000  0.024457  0.023889   
Y2014          0.006164   0.021722      0.024457  1.000000  0.994647   
Y2015          0.005472   0.020857      0.023889  0.994647  1.000000   
Y2016          0.005247   0.020109      0.023444  0.996081  0.995739   
Y2017          0.005006   0.021494      0.024254  0.995230  0.988048   
Y2018          0.005665   0.021314      0.024279  0.994872  0.988208   

                 Y2016     Y2017     Y2018  
Area Code     0.005247  0.005006  0.005665  
Item Code     0.020109  0.021494  0.021314  
Element Code  0.023444  0.024254  0.024279  
Y2014         0.996081  0.995230  0.994872  
Y2015         0.995739  0.988048  0.988208  
Y2016         1.000000  0.992785  0.992757  
Y2017         0.992785  1.000000  0.998103  
Y2018         0.992757  0.998103  1.000000

In [32]:
#The year 2017 has the highest sum of Import Quantity
A = df[df.Element == 'Import Quantity']
A.Y2014.sum(),A.Y2015.sum(), A.Y2016.sum(),A.Y2017.sum(),A.Y2018.sum

(274144.48,
 267018.45999999996,
 286582.78,
 294559.09,
 <bound method Series.sum of 12       13182.0
 28        8434.0
 44         207.0
 59         402.0
 74        4126.0
           ...   
 60897        0.0
 60905        0.0
 60913       16.0
 60923        0.0
 60933       16.0
 Name: Y2018, Length: 5139, dtype: float64>)

In [34]:
#The total number of Domestic supply qty in 2014 is 1996716.35

df.groupby('Element')['Y2014'].sum()

Element
Domestic supply quantity                  1996716.35
Export Quantity                            150020.64
Fat supply quantity (g/capita/day)          10225.56
Feed                                       216927.89
Food                                      1212332.49
Food supply (kcal/capita/day)              454257.00
Food supply quantity (kg/capita/yr)         49650.63
Import Quantity                            274144.48
Losses                                     153223.00
Other uses (non-food)                       78718.13
Processing                                 282923.00
Production                                1931287.75
Protein supply quantity (g/capita/day)      11836.46
Residuals                                   30149.00
Seed                                        21922.92
Stock Variation                             58749.83
Total Population - Both sexes             1031585.00
Tourist consumption                           416.00
Name: Y2014, dtype: float64

In [36]:
#The Domestic supply quantity has the highest sum among the elements in 2018
df.groupby('Element')['Y2018'].sum()

Element
Domestic supply quantity                  2161192.10
Export Quantity                            181594.80
Fat supply quantity (g/capita/day)          10258.69
Feed                                       233489.68
Food                                      1303841.28
Food supply (kcal/capita/day)              455261.00
Food supply quantity (kg/capita/yr)         49056.85
Import Quantity                            287997.09
Losses                                     163902.00
Other uses (non-food)                       91300.97
Processing                                 308429.00
Production                                2075072.89
Protein supply quantity (g/capita/day)      11833.56
Residuals                                   34864.00
Seed                                        25263.14
Stock Variation                             20577.91
Total Population - Both sexes             1140605.00
Tourist consumption                            90.00
Name: Y2018, dtype: float64

In [38]:
#The total Import Quantity in Egypt in 2018 is  53954.20
# note that A has been defined for import quantity before
A = df[df.Element == 'Import Quantity']
A.groupby("Area")['Y2018'].sum()

Area
Algeria                        36238.29
Angola                          7769.67
Benin                           7008.24
Botswana                        1908.42
Burkina Faso                    2605.64
Cabo Verde                       499.66
Cameroon                        4188.88
Central African Republic          75.02
Chad                             491.95
Comoros                            2.92
Congo                           1785.27
Côte d'Ivoire                   9271.21
Djibouti                        3784.92
Egypt                          53954.20
Eswatini                         936.53
Ethiopia                        5655.24
Ethiopia PDR                       0.00
Gabon                           1079.75
Gambia                          1212.10
Ghana                           9914.68
Guinea                          4707.95
Guinea-Bissau                    497.72
Kenya                          11188.96
Lesotho                         1016.97
Liberia                         120

In [40]:
#The total number of unique countries in the dataset is 49
len(set(df.Area))

49